### ISSUE TITLE
Golang refactor stage 1 - passing rule

### ISSUE THREAD

**Issue by sublimino** [controlplaneio/kubesec#1]
An example passing rule to check:

```json
{
  "selector": "containers[] .securityContext .runAsUser > 1000",
  "reason": "Force the running image to run as a non-root user to ensure least privilege",
  "points": 1
}
```

Example resource to check against:

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: run-as-user-99999
          image: redis:alpine
          securityContext:
            runAsUser: 99999
```

Desired output:

```json
{
  "score": 1,
  "scoring": {
    "critical": [],
    "advise": []
  }
}
```
