### ISSUE TITLE
Golang refactor stage 2 - failing rule

### ISSUE THREAD

**Issue by sublimino** [controlplaneio/kubesec#2]
An example failing rule to check:

```json
{
  "selector": ".spec .hostNetwork == true",
  "reason": "Sharing the host's network namespace permits processes in the pod to communicate with processes bound to the host's loopback adapter",
  "weight": 0,
  "points": -9,
  "href": null
}
```

Example resource to check against (empty security context, key could also be absent):

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: hostnetwork-true
          image: redis:alpine
          hostNetwork: true
```

Example output:

```json
{
  "score": -9,
  "scoring": {
    "critical": [
      {
        "selector": ".spec .hostNetwork",
        "reason": "Sharing the host's network namespace permits processes in the pod to communicate with processes bound to the host's loopback adapter",
        "weight": 0
      }
    ],
    "advise": []
  }
}
```
