### ISSUE TITLE
.spec.securityContext.runAsNonRoot not considered as secure configuration

### ISSUE THREAD

**Issue by romansil** [controlplaneio/kubesec#329]
**Describe the bug**

`runAsNonRoot` can be defined on two places:
- Pod level: `.spec.securityContext.runAsNonRoot`
- Container level: `.spec.containers[].securityContext.runAsNonRoot`

As mentioned in the notes of this [Kubesec documentation page](https://kubesec.io/basics/containers-securitycontext-runasnonroot-true/): "Container level security context settings are applied to the specific container and override settings made at the pod level where there is overlap". 
Setting `runAsNonRoot` on pod level is secure as well and should be parsed by Kubesec.

**To Reproduce**

Test the following manifest with Kubesec:
```yml
apiVersion: v1
kind: Pod
metadata:
  name: poc
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: tryout
      image: nginx
```

**Expected behaviour**
The advise for missing `runAsNonRoot` should not be reported if it's specified on Pod level.

**Additional context**
API documentation for both options:
- Pod level: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context
- Container level: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1
