### ISSUE TITLE
.spec.hostAliases not recognized in deployment

### ISSUE THREAD

**Issue by d47zm3** [controlplaneio/kubesec#47]
Despite of having hostAliases specified, kubesec reports it's as missing, here's YAML and result of POST to kubesec.io
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "stage-release-name"
  labels:
    chart: "stage-release-name"
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    container.apparmor.security.beta.kubernetes.io/components: runtime/default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "stage-release-name"
      annotations:
        checksum/config: b1cf7597ae2790dd889ef159dada9f7224896753a0a53399fd6fbb695b402ca9
    spec:
      automountServiceAccountToken: false
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "localhost"
      serviceAccountName: "default"
      containers:
        - name: components
          image: "eu.gcr.io/project/components:13a44d56811f67e1709775ea987838eb257b3163"
          imagePullPolicy: Always
          ports:
          - name: nginx-port
            containerPort: 8080
            protocol: TCP
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-temporary
            mountPath: /tmp
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
          readinessProbe:
            httpGet:
              path: /
              port: nginx-port
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: nginx-port
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsNonRoot: true
      volumes:
      - name: nginx-config
        configMap:
          name: "stage-release-name-nginx-configmap"
      - name: nginx-temporary
        emptyDir: {}
```

Result:
```
curl -sSX POST --data-binary @"error.yaml" https://v2.kubesec.io/scan

[
  {
    "object": "Deployment/stage-release-name.default",
    "valid": true,
    "message": "Passed with a score of 13 points",
    "score": 13,
    "scoring": {
      "critical": [
        {
          "selector": ".spec .hostAliases",
          "reason": "Managing /etc/hosts aliases can prevent the container from modifying the file after a pod's containers have already been started. DNS should be managed by the orchestrator"
        }
      ]
    }
  }
]
```

Kubeval reports valid deployment as well
```
kubeval error.yaml
The document error.yaml contains a valid Deployment
```
