### ISSUE TITLE
kubesec not taking sufficient umbrage at `allowPrivilegeEscalation: true`

### ISSUE THREAD

**Issue by lukebond** [controlplaneio/kubesec#51]
e.g. yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
  namespace: deployer
  labels:
    app: teamcity-server
spec:
  selector:
    matchLabels:
      app: teamcity-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
      - image: jetbrains/teamcity-server:2019.1-linux
        imagePullPolicy: IfNotPresent
        name: teamcity-server
        ports:
        - containerPort: 8111
          protocol: TCP
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: TEAMCITY_SERVER_MEM_OPTS
          valueFrom:
            configMapKeyRef:
              name: teamcity-server-env
              key: MEM_OPTS_VALUE
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data/teamcity_server/datadir
          name: teamcity-server-storage
        - mountPath: /opt/teamcity/logs
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: teamcity-server-storage
        persistentVolumeClaim:
          claimName: teamcity-server-config
      - hostPath:
          path: /mnt/logs
          type: DirectoryOrCreate
        name: logs
      serviceAccountName: teamcity-service-account
```

Reports the following results:

```json
[
  {
    "object": "Deployment/teamcity-server.deployer",
    "valid": true,
    "message": "Passed with a score of 7 points",
    "score": 7,
    "scoring": {
      "advise": [
        {
          "selector": ".metadata .annotations .\"container.seccomp.security.alpha.kubernetes.io/pod\"",
          "reason": "Seccomp profiles set minimum privilege and secure against unknown threats"
        },
        {
          "selector": "containers[] .securityContext .capabilities .drop | index(\"ALL\")",
          "reason": "Drop all capabilities and add only those required to reduce syscall attack surface"
        },
        {
          "selector": "containers[] .securityContext .runAsUser -gt 10000",
          "reason": "Run as a high-UID user to avoid conflicts with the host's user table"
        },
        {
          "selector": "containers[] .securityContext .readOnlyRootFilesystem == true",
          "reason": "An immutable root filesystem can prevent malicious binaries being added to PATH and increase attack cost"
        },
        {
          "selector": "containers[] .securityContext .runAsNonRoot == true",
          "reason": "Force the running image to run as a non-root user to ensure least privilege"
        },
        {
          "selector": "containers[] .securityContext .capabilities .drop",
          "reason": "Reducing kernel capabilities available to a container limits its attack surface"
        },
        {
          "selector": ".metadata .annotations .\"container.apparmor.security.beta.kubernetes.io/nginx\"",
          "reason": "Well defined AppArmor policies may provide greater protection from unknown threats. WARNING: NOT PRODUCTION READY"
        }
      ]
    }
  }
]
```

I would expect to lose points for this.
