### ISSUE TITLE
Linting demo does not work with default example

### ISSUE THREAD

**Issue by Zigzauer** [controlplaneio/kubesec#81]
Demo on https://kubesec.io home does not work with sample file.
Error output:
```
[
  {
    "object": "Pod/kubesec-demo.default",
    "valid": false,
    "message": "resource.json: Missing 'apiVersion' key",
    "score": 0,
    "scoring": {}
  }
]
```

**Comment by 06kellyjac** [comment]
Ok so this issue is due to the POST request looking as follows and attaching `file=` before the payload:

```
file=apiVersion: v1
kind: Pod
metadata:
  name: kubesec-demo
spec:
  containers:
  - name: kubesec-demo
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      readOnlyRootFilesystem: true

```

I'll get on this now
